apiVersion: v1
kind: Service
metadata:
  name: httpbin2
  namespace: httpbin2
  labels:
    app: httpbin2
    service: httpbin2
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: httpbin
  type: LoadBalancer